# This is a failed attempt of configuring cloudformation

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  attemptsLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::898534877678:role/service-role/attemptsLambda-role-al7p15p7'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopicAttempts
      VpcConfig:
        SecurityGroupIds:
          - sg-0054013568a3a81af
        SubnetIds:
          - subnet-08e2ef243c29b3249
          - subnet-040d5176084377e1f
          - subnet-01f565dbd127ea0d6
          - subnet-0e323d2637443d680
          - subnet-0da85781b8ac6ad18
          - subnet-0fa07fe10136c0287
      Layers:
        - 'arn:aws:lambda:us-east-1:898534877678:layer:pymysql_layer:1'
  SNSTopicAttempts:
    Type: 'AWS::SNS::Topic'
  recievedLamda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::898534877678:role/service-role/recievedLamda-role-zwqjk03v'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopicRecieved
      VpcConfig:
        SecurityGroupIds:
          - sg-0054013568a3a81af
        SubnetIds:
          - subnet-08e2ef243c29b3249
          - subnet-040d5176084377e1f
          - subnet-01f565dbd127ea0d6
          - subnet-0e323d2637443d680
          - subnet-0da85781b8ac6ad18
          - subnet-0fa07fe10136c0287
      Layers:
        - 'arn:aws:lambda:us-east-1:898534877678:layer:pymysql_layer:1'
  SNSTopicRecieved:
    Type: 'AWS::SNS::Topic'
